-- MySQL Script generated by MySQL Workbench
-- Wed May 15 20:57:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wrcFantasy
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `wrcFantasy`;

CREATE SCHEMA IF NOT EXISTS `wrcFantasy` DEFAULT CHARACTER SET utf8 ;
USE `wrcFantasy` ;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Uporabnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Uporabnik` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Uporabnik` (
  `idUporabnik` INT NOT NULL AUTO_INCREMENT,
  `uporabnisko_ime` VARCHAR(255) NOT NULL,
  `geslo` VARCHAR(255) NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`idUporabnik`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Liga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Liga` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Liga` (
  `idLiga` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(255) NOT NULL,
  `id_lastnika` INT NOT NULL,
  PRIMARY KEY (`idLiga`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Uporabnik_has_Liga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Uporabnik_has_Liga` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Uporabnik_has_Liga` (
  `Uporabnik_idUporabnik` INT NOT NULL,
  `Liga_idLiga` INT NOT NULL,
  PRIMARY KEY (`Uporabnik_idUporabnik`, `Liga_idLiga`),
  INDEX `fk_Uporabnik_has_Liga_Liga1_idx` (`Liga_idLiga` ASC),
  INDEX `fk_Uporabnik_has_Liga_Uporabnik_idx` (`Uporabnik_idUporabnik` ASC),
  CONSTRAINT `fk_Uporabnik_has_Liga_Uporabnik`
    FOREIGN KEY (`Uporabnik_idUporabnik`)
    REFERENCES `wrcFantasy`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uporabnik_has_Liga_Liga1`
    FOREIGN KEY (`Liga_idLiga`)
    REFERENCES `wrcFantasy`.`Liga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Nabor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Nabor` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Nabor` (
  `idNabor` INT NOT NULL AUTO_INCREMENT,
  `Uporabnik_idUporabnik` INT NOT NULL,
  `Liga_idLiga` INT NOT NULL,
  PRIMARY KEY (`idNabor`, `Uporabnik_idUporabnik`, `Liga_idLiga`),
  INDEX `fk_Nabor_Uporabnik1_idx` (`Uporabnik_idUporabnik` ASC),
  INDEX `fk_Nabor_Liga1_idx` (`Liga_idLiga` ASC),
  CONSTRAINT `fk_Nabor_Uporabnik1`
    FOREIGN KEY (`Uporabnik_idUporabnik`)
    REFERENCES `wrcFantasy`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nabor_Liga1`
    FOREIGN KEY (`Liga_idLiga`)
    REFERENCES `wrcFantasy`.`Liga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Ekipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Ekipe` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Ekipe` (
  `idEkipe` INT NOT NULL,
  `ime` VARCHAR(255) NOT NULL,
  `cena` INT NOT NULL,
  PRIMARY KEY (`idEkipe`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Vozniki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Vozniki` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Vozniki` (
  `idVoznika` INT NOT NULL AUTO_INCREMENT,
  `ime in priimek` VARCHAR(255) NOT NULL,
  `cena` INT NOT NULL,
  `img_src` VARCHAR(255) NULL,
  `Ekipe_idEkipe` INT NOT NULL,
  PRIMARY KEY (`idVoznika`, `Ekipe_idEkipe`),
  INDEX `fk_Vozniki_Ekipe1_idx` (`Ekipe_idEkipe` ASC),
  CONSTRAINT `fk_Vozniki_Ekipe1`
    FOREIGN KEY (`Ekipe_idEkipe`)
    REFERENCES `wrcFantasy`.`Ekipe` (`idEkipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Nabor_has_Vozniki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Nabor_has_Vozniki` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Nabor_has_Vozniki` (
  `Nabor_idNabor` INT NOT NULL,
  `Vozniki_idVoznika` INT NOT NULL,
  `Vozniki_Ekipe_idEkipe` INT NOT NULL,
  PRIMARY KEY (`Nabor_idNabor`, `Vozniki_idVoznika`, `Vozniki_Ekipe_idEkipe`),
  INDEX `fk_Nabor_has_Vozniki_Vozniki1_idx` (`Vozniki_idVoznika` ASC, `Vozniki_Ekipe_idEkipe` ASC),
  INDEX `fk_Nabor_has_Vozniki_Nabor1_idx` (`Nabor_idNabor` ASC),
  CONSTRAINT `fk_Nabor_has_Vozniki_Nabor1`
    FOREIGN KEY (`Nabor_idNabor`)
    REFERENCES `wrcFantasy`.`Nabor` (`idNabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nabor_has_Vozniki_Vozniki1`
    FOREIGN KEY (`Vozniki_idVoznika`, `Vozniki_Ekipe_idEkipe`)
    REFERENCES `wrcFantasy`.`Vozniki` (`idVoznika`, `Ekipe_idEkipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Nabor_has_Ekipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Nabor_has_Ekipe` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Nabor_has_Ekipe` (
  `Nabor_idNabor` INT NOT NULL,
  `Ekipe_idEkipe` INT NOT NULL,
  PRIMARY KEY (`Nabor_idNabor`, `Ekipe_idEkipe`),
  INDEX `fk_Nabor_has_Ekipe_Ekipe1_idx` (`Ekipe_idEkipe` ASC),
  INDEX `fk_Nabor_has_Ekipe_Nabor1_idx` (`Nabor_idNabor` ASC),
  CONSTRAINT `fk_Nabor_has_Ekipe_Nabor1`
    FOREIGN KEY (`Nabor_idNabor`)
    REFERENCES `wrcFantasy`.`Nabor` (`idNabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nabor_has_Ekipe_Ekipe1`
    FOREIGN KEY (`Ekipe_idEkipe`)
    REFERENCES `wrcFantasy`.`Ekipe` (`idEkipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
