-- MySQL Script generated by MySQL Workbench
-- Wed May 15 20:57:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wrcFantasy
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `wrcFantasy`;

CREATE SCHEMA IF NOT EXISTS `wrcFantasy` DEFAULT CHARACTER SET utf8 ;
USE `wrcFantasy` ;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Uporabnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Uporabnik` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Uporabnik` (
  `idUporabnik` INT NOT NULL AUTO_INCREMENT,
  `uporabnisko_ime` VARCHAR(255) NOT NULL,
  `geslo` VARCHAR(255) NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`idUporabnik`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Liga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Liga` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Liga` (
  `idLiga` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(255) NOT NULL,
  `id_lastnika` INT NOT NULL,
  PRIMARY KEY (`idLiga`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Uporabnik_has_Liga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Uporabnik_has_Liga` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Uporabnik_has_Liga` (
  `Uporabnik_idUporabnik` INT NOT NULL,
  `Liga_idLiga` INT NOT NULL,
  PRIMARY KEY (`Uporabnik_idUporabnik`, `Liga_idLiga`),
  INDEX `fk_Uporabnik_has_Liga_Liga1_idx` (`Liga_idLiga` ASC),
  INDEX `fk_Uporabnik_has_Liga_Uporabnik_idx` (`Uporabnik_idUporabnik` ASC),
  CONSTRAINT `fk_Uporabnik_has_Liga_Uporabnik`
    FOREIGN KEY (`Uporabnik_idUporabnik`)
    REFERENCES `wrcFantasy`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uporabnik_has_Liga_Liga1`
    FOREIGN KEY (`Liga_idLiga`)
    REFERENCES `wrcFantasy`.`Liga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Nabor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Nabor` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Nabor` (
  `idNabor` INT NOT NULL AUTO_INCREMENT,
  `Uporabnik_idUporabnik` INT NOT NULL,
  `Liga_idLiga` INT NOT NULL,
  PRIMARY KEY (`idNabor`, `Uporabnik_idUporabnik`, `Liga_idLiga`),
  INDEX `fk_Nabor_Uporabnik1_idx` (`Uporabnik_idUporabnik` ASC),
  INDEX `fk_Nabor_Liga1_idx` (`Liga_idLiga` ASC),
  CONSTRAINT `fk_Nabor_Uporabnik1`
    FOREIGN KEY (`Uporabnik_idUporabnik`)
    REFERENCES `wrcFantasy`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nabor_Liga1`
    FOREIGN KEY (`Liga_idLiga`)
    REFERENCES `wrcFantasy`.`Liga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Ekipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Ekipe` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Ekipe` (
  `idEkipe` INT NOT NULL,
  `ime` VARCHAR(255) NOT NULL,
  `cena` INT NOT NULL,
  `img_src` TEXT,
  PRIMARY KEY (`idEkipe`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Vozniki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Vozniki` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Vozniki` (
  `idVoznika` INT NOT NULL AUTO_INCREMENT,
  `ime in priimek` VARCHAR(255) NOT NULL,
  `cena` INT NOT NULL,
  `img_src` TEXT NULL,
  `Ekipe_idEkipe` INT NOT NULL,
  PRIMARY KEY (`idVoznika`, `Ekipe_idEkipe`),
  INDEX `fk_Vozniki_Ekipe1_idx` (`Ekipe_idEkipe` ASC),
  CONSTRAINT `fk_Vozniki_Ekipe1`
    FOREIGN KEY (`Ekipe_idEkipe`)
    REFERENCES `wrcFantasy`.`Ekipe` (`idEkipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Nabor_has_Vozniki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Nabor_has_Vozniki` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Nabor_has_Vozniki` (
  `Nabor_idNabor` INT NOT NULL,
  `Vozniki_idVoznika` INT NOT NULL,
  `Vozniki_Ekipe_idEkipe` INT NOT NULL,
  PRIMARY KEY (`Nabor_idNabor`, `Vozniki_idVoznika`, `Vozniki_Ekipe_idEkipe`),
  INDEX `fk_Nabor_has_Vozniki_Vozniki1_idx` (`Vozniki_idVoznika` ASC, `Vozniki_Ekipe_idEkipe` ASC),
  INDEX `fk_Nabor_has_Vozniki_Nabor1_idx` (`Nabor_idNabor` ASC),
  CONSTRAINT `fk_Nabor_has_Vozniki_Nabor1`
    FOREIGN KEY (`Nabor_idNabor`)
    REFERENCES `wrcFantasy`.`Nabor` (`idNabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nabor_has_Vozniki_Vozniki1`
    FOREIGN KEY (`Vozniki_idVoznika`, `Vozniki_Ekipe_idEkipe`)
    REFERENCES `wrcFantasy`.`Vozniki` (`idVoznika`, `Ekipe_idEkipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Nabor_has_Ekipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Nabor_has_Ekipe` ;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Nabor_has_Ekipe` (
  `Nabor_idNabor` INT NOT NULL,
  `Ekipe_idEkipe` INT NOT NULL,
  PRIMARY KEY (`Nabor_idNabor`, `Ekipe_idEkipe`),
  INDEX `fk_Nabor_has_Ekipe_Ekipe1_idx` (`Ekipe_idEkipe` ASC),
  INDEX `fk_Nabor_has_Ekipe_Nabor1_idx` (`Nabor_idNabor` ASC),
  CONSTRAINT `fk_Nabor_has_Ekipe_Nabor1`
    FOREIGN KEY (`Nabor_idNabor`)
    REFERENCES `wrcFantasy`.`Nabor` (`idNabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nabor_has_Ekipe_Ekipe1`
    FOREIGN KEY (`Ekipe_idEkipe`)
    REFERENCES `wrcFantasy`.`Ekipe` (`idEkipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wrcFantasy`.`Leaderboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrcFantasy`.`Leaderboard`;

CREATE TABLE IF NOT EXISTS `wrcFantasy`.`Leaderboard` (
  `idLeaderboard` INT NOT NULL AUTO_INCREMENT,
  `id_uporabnika` INT NOT NULL,
  `tocke` INT NOT NULL,
  `id_lige` INT NOT NULL,
  PRIMARY KEY (`idLeaderboard`),
  CONSTRAINT `fk_Leaderboard_Uporabnik`
    FOREIGN KEY (`id_uporabnika`)
    REFERENCES `wrcFantasy`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leaderboard_Liga`
    FOREIGN KEY (`id_lige`)
    REFERENCES `wrcFantasy`.`Liga` (`idLiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Inserting data into Ekipe (Teams) table
INSERT INTO `wrcFantasy`.`Ekipe` (`idEkipe`, `ime`, `cena`, `img_src`)
VALUES
    (1, 'Hyundai Shell Mobis World Rally Team', 35, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vODM0ODQ2NjEtOGQxNy00YzM5LTk5NTEtNTU0ZTE2ZGI3ZDkxX2h5dW5kYWktaTIwLXdyYy1yYWxseTEtMjAyNC5qcGciLCJ0aW1lc3RhbXAiOiIyMDI0LTAxLTI0VDEzOjUyOjIwLjQ0M1oiLCJlZGl0cyI6eyJleHRyYWN0Ijp7ImxlZnQiOjAsInRvcCI6MCwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MH0sInJlc2l6ZSI6eyJ3aWR0aCI6MTI4MCwiaGVpZ2h0Ijo3MjB9LCJqcGVnIjp7InF1YWxpdHkiOjEwMH19fQ==/83484661-8d17-4c39-9951-554e16db7d91_hyundai-i20-wrc-rally1-2024.jpg"),
    (2, 'M-Sport Ford World Rally Team', 30, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vN2NkZGU0YjctNTY1My00NWVkLWE5YzMtZjg5MjVkODM5YjQyX2ZvcmQtcHVtYS13cmMtcmFsbHkxLTIwMjQuanBnIiwidGltZXN0YW1wIjoiMjAyNC0wMS0yNFQxMzo1MjoyMC4xNTZaIiwiZWRpdHMiOnsiZXh0cmFjdCI6eyJsZWZ0IjowLCJ0b3AiOjAsIndpZHRoIjoxOTIwLCJoZWlnaHQiOjEwODB9LCJyZXNpemUiOnsid2lkdGgiOjEyODAsImhlaWdodCI6NzIwfSwianBlZyI6eyJxdWFsaXR5IjoxMDB9fX0=/7cdde4b7-5653-45ed-a9c3-f8925d839b42_ford-puma-wrc-rally1-2024.jpg"),
    (3, 'Toyota Gazoo Racing World Team', 25, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vYzYwZjdhYTQtYmM4Ni00Njc1LWE4NTgtNDkzOWE5NDU5ZDY4X3RveW90YS1nci15YXJpcy13cmMtcmFsbHkxLTIwMjQuanBnIiwidGltZXN0YW1wIjoiMjAyNC0wMS0yNFQxMzo1MjoyMC4yNjhaIiwiZWRpdHMiOnsiZXh0cmFjdCI6eyJsZWZ0IjowLCJ0b3AiOjAsIndpZHRoIjoxOTIwLCJoZWlnaHQiOjEwODB9LCJyZXNpemUiOnsid2lkdGgiOjEyODAsImhlaWdodCI6NzIwfSwianBlZyI6eyJxdWFsaXR5IjoxMDB9fX0=/c60f7aa4-bc86-4675-a858-4939a9459d68_toyota-gr-yaris-wrc-rally1-2024.jpg");

-- Inserting data into Vozniki (Drivers) table
INSERT INTO `wrcFantasy`.`Vozniki` (`idVoznika`, `ime in priimek`, `cena`, `Ekipe_idEkipe`, `img_src`)
VALUES
    (1, 'Lorenzo Bertelli', 8, 3, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vNjg4NTNjZjctMGY3NS00M2Q2LTkzNTktOTIxNDIwYzE5ZDczX2JlcnRlbGxpLmpwZyIsInRpbWVzdGFtcCI6IjIwMjMtMDgtMThUMTI6NTA6MDQuMDg1WiIsImVkaXRzIjp7ImV4dHJhY3QiOnsibGVmdCI6MCwidG9wIjowLCJ3aWR0aCI6MTkyMCwiaGVpZ2h0IjoxMDgwfSwicmVzaXplIjp7IndpZHRoIjo0ODAsImhlaWdodCI6MjcwfSwianBlZyI6eyJxdWFsaXR5IjoxMDB9fX0=/68853cf7-0f75-43d6-9359-921420c19d73_bertelli.jpg"), -- Toyota
    (2, 'Esapekka Lappi', 11, 1, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vMDFmMDM4NmEtYmEwZi00OTY1LTlkYzYtNzAwZjBiNTU2NDM2X2VzYXBla2thbGFwcGkuanBnIiwidGltZXN0YW1wIjoiMjAyNC0wNC0xOVQwOTo0NjoxMi4yNTRaIiwiZWRpdHMiOnsiZXh0cmFjdCI6eyJsZWZ0IjowLCJ0b3AiOjAsIndpZHRoIjoxOTIwLCJoZWlnaHQiOjEwODB9LCJyZXNpemUiOnsid2lkdGgiOjQ4MCwiaGVpZ2h0IjoyNzB9LCJqcGVnIjp7InF1YWxpdHkiOjEwMH19fQ==/01f0386a-ba0f-4965-9dc6-700f0b556436_esapekkalappi.jpg"),    -- Hyundai
    (3, 'Elfyn Evans', 17, 3, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vZjRlZjQxMzAtN2ZhOC00OWU0LWFmYTQtYWM4ODliOGU1NGE0X2VsZnluLWV2YW5zLTIwMjQuanBnIiwidGltZXN0YW1wIjoiMjAyNC0wMS0yMlQxMTozMzo1OS43NjVaIiwiZWRpdHMiOnsiZXh0cmFjdCI6eyJsZWZ0IjowLCJ0b3AiOjAsIndpZHRoIjoxOTIwLCJoZWlnaHQiOjEwODB9LCJyZXNpemUiOnsid2lkdGgiOjQ4MCwiaGVpZ2h0IjoyNzB9LCJqcGVnIjp7InF1YWxpdHkiOjEwMH19fQ==/f4ef4130-7fa8-49e4-afa4-ac889b8e54a4_elfyn-evans-2024.jpg"),        -- Toyota
    (4, 'Adrien Fourmaux', 15, 2, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vMWQ2OGQ5N2ItYWZjNy00OTM4LTk3N2MtZWJjYTJkMTYwYmU3X2Fkcmllbi1mb3VybWF1eC0yMDI0LmpwZyIsInRpbWVzdGFtcCI6IjIwMjQtMDEtMjJUMTE6MzM6NTkuNzk4WiIsImVkaXRzIjp7ImV4dHJhY3QiOnsibGVmdCI6MCwidG9wIjowLCJ3aWR0aCI6MTkyMCwiaGVpZ2h0IjoxMDgwfSwicmVzaXplIjp7IndpZHRoIjo0ODAsImhlaWdodCI6MjcwfSwianBlZyI6eyJxdWFsaXR5IjoxMDB9fX0=/1d68d97b-afc7-4938-977c-ebca2d160be7_adrien-fourmaux-2024.jpg"),    -- M-Sport
    (5, 'Takamoto Katsuta', 13, 3, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vOTYyNjg2NDQtZmQwNC00OGU2LWIzYjItMDhiMmY3ODI2YzcyX3Rha2Ftb3RvLWthdHN1dGEyMDI0LmpwZyIsInRpbWVzdGFtcCI6IjIwMjQtMDEtMjJUMTE6MzM6NTkuNzgzWiIsImVkaXRzIjp7ImV4dHJhY3QiOnsibGVmdCI6MCwidG9wIjowLCJ3aWR0aCI6MTkyMCwiaGVpZ2h0IjoxMDgwfSwicmVzaXplIjp7IndpZHRoIjo0ODAsImhlaWdodCI6MjcwfSwianBlZyI6eyJxdWFsaXR5IjoxMDB9fX0=/96268644-fd04-48e6-b3b2-08b2f7826c72_takamoto-katsuta2024.jpg"),   -- Toyota
    (6, 'Grégoire Munster', 8, 2, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vZTI5NWI5NDMtOWQ4ZS00MjRlLTgzNmYtNTIyZDdlMDhiMDA1X2dyZWdvaXJlLW11bnN0ZXItMjAyNC5qcGciLCJ0aW1lc3RhbXAiOiIyMDI0LTAxLTIyVDExOjMzOjU5Ljc3M1oiLCJlZGl0cyI6eyJleHRyYWN0Ijp7ImxlZnQiOjAsInRvcCI6MCwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MH0sInJlc2l6ZSI6eyJ3aWR0aCI6NDgwLCJoZWlnaHQiOjI3MH0sImpwZWciOnsicXVhbGl0eSI6MTAwfX19/e295b943-9d8e-424e-836f-522d7e08b005_gregoire-munster-2024.jpg"),   -- M-Sport
    (7, 'Sébastien Ogier', 14, 3, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vMzk5YzI2MTYtNTY3NS00MjQ0LWI5YzUtZThiMTA0N2Y0MmNiX3NlYmFzdGllbi1vZ2llci0yMDI0LmpwZyIsInRpbWVzdGFtcCI6IjIwMjQtMDEtMjJUMTE6MzM6NTkuNzI1WiIsImVkaXRzIjp7ImV4dHJhY3QiOnsibGVmdCI6MCwidG9wIjowLCJ3aWR0aCI6MTkyMCwiaGVpZ2h0IjoxMDgwfSwicmVzaXplIjp7IndpZHRoIjo0ODAsImhlaWdodCI6MjcwfSwianBlZyI6eyJxdWFsaXR5IjoxMDB9fX0=/399c2616-5675-4244-b9c5-e8b1047f42cb_sebastien-ogier-2024.jpg"),    -- Toyota
    (8, 'Thierry Neuville', 18, 1, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vZmJlYmZlNGUtYjc4ZC00ZWNiLTg5ZDQtZmRkZGY1NzFmY2NhX3RoaWVycnktbmV1dmlsbGUuanBnIiwidGltZXN0YW1wIjoiMjAyNC0wNC0xOVQwOTo0NjoxMS41MDRaIiwiZWRpdHMiOnsiZXh0cmFjdCI6eyJsZWZ0IjowLCJ0b3AiOjAsIndpZHRoIjoxOTIwLCJoZWlnaHQiOjEwODB9LCJyZXNpemUiOnsid2lkdGgiOjQ4MCwiaGVpZ2h0IjoyNzB9LCJqcGVnIjp7InF1YWxpdHkiOjEwMH19fQ==/fbebfe4e-b78d-4ecb-89d4-fdddf571fcca_thierry-neuville.jpg"),   -- Hyundai
    (9, 'Kalle Rovanperä', 12, 3, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vYTFkMzIxYjUtNGVjNy00MWUyLWI1MjAtZWM5ZmY3ZjY1NmZlX3JvdmFucGVyYS5qcGciLCJ0aW1lc3RhbXAiOiIyMDIzLTA4LTE4VDEyOjUwOjAzLjQ2N1oiLCJlZGl0cyI6eyJleHRyYWN0Ijp7ImxlZnQiOjAsInRvcCI6MCwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MH0sInJlc2l6ZSI6eyJ3aWR0aCI6NDgwLCJoZWlnaHQiOjI3MH0sImpwZWciOnsicXVhbGl0eSI6MTAwfX19/a1d321b5-4ec7-41e2-b520-ec9ff7f656fe_rovanpera.jpg"),    -- Toyota
    (10, 'Dani Sordo', 9, 1, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vY2RiYmYwOWYtYjA4NC00ZjM4LWJkNTYtM2U2YzA3NTU1MGQ3X2Rhbmktc29yZG8tZXMtMjAyNC5qcGciLCJ0aW1lc3RhbXAiOiIyMDI0LTAxLTE4VDE2OjAyOjQwLjk0NloiLCJlZGl0cyI6eyJleHRyYWN0Ijp7ImxlZnQiOjAsInRvcCI6MCwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MH0sInJlc2l6ZSI6eyJ3aWR0aCI6NDgwLCJoZWlnaHQiOjI3MH0sImpwZWciOnsicXVhbGl0eSI6MTAwfX19/cdbbf09f-b084-4f38-bd56-3e6c075550d7_dani-sordo-es-2024.jpg"),        -- Hyundai
    (11, 'Ott Tänak', 16, 1, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vNDg0MDcwNDAtNTUyYy00Njg1LTk1NmEtMDdhN2E1MDQxNjUyX290dC10YW5hay5qcGciLCJ0aW1lc3RhbXAiOiIyMDI0LTA0LTE5VDA5OjQ2OjEyLjM0MFoiLCJlZGl0cyI6eyJleHRyYWN0Ijp7ImxlZnQiOjAsInRvcCI6MCwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MH0sInJlc2l6ZSI6eyJ3aWR0aCI6NDgwLCJoZWlnaHQiOjI3MH0sImpwZWciOnsicXVhbGl0eSI6MTAwfX19/48407040-552c-4685-956a-07a7a5041652_ott-tanak.jpg"),         -- Hyundai
    (12, 'Andreas Mikkelsen', 10, 1, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vNzcwM2E2YjAtZWE4Yi00NWI0LTg0YTUtN2ExODQ5MjVlNTU5X2FuZHJlYXMtbWlra2Vsc2VuLmpwZyIsInRpbWVzdGFtcCI6IjIwMjQtMDQtMTlUMDk6NDY6MTEuMzA0WiIsImVkaXRzIjp7ImV4dHJhY3QiOnsibGVmdCI6MCwidG9wIjowLCJ3aWR0aCI6MTkyMCwiaGVpZ2h0IjoxMDgwfSwicmVzaXplIjp7IndpZHRoIjo0ODAsImhlaWdodCI6MjcwfSwianBlZyI6eyJxdWFsaXR5IjoxMDB9fX0=/7703a6b0-ea8b-45b4-84a5-7a184925e559_andreas-mikkelsen.jpg"), -- Hyundai
    (13, 'Jourdan Serderidis', 8, 2, "https://wrc.enhance.diagnal.com/resources/images/eyJrZXkiOiJodHRwczovL2VuaGFuY2Utc3RvcmFnZS1zdGFjay1wcm9kLXdyY21lZGlhZmlsZXN0b3JhZ2UtZzN6MmhnM3Vyd2ZmLnMzLmFtYXpvbmF3cy5jb20vZDZkZmUxMTUtODYwNy00ZjhjLTlkNDktODk2ODViOTkzNjQxX2pvdXJkYW4tc2VyZGVyaWRpcy5qcGciLCJ0aW1lc3RhbXAiOiIyMDI0LTA0LTE5VDA5OjQ2OjEyLjU5MloiLCJlZGl0cyI6eyJleHRyYWN0Ijp7ImxlZnQiOjAsInRvcCI6MCwid2lkdGgiOjE5MjAsImhlaWdodCI6MTA4MH0sInJlc2l6ZSI6eyJ3aWR0aCI6NDgwLCJoZWlnaHQiOjI3MH0sImpwZWciOnsicXVhbGl0eSI6MTAwfX19/d6dfe115-8607-4f8c-9d49-89685b993641_jourdan-serderidis.jpg");-- M-Sport
